- name: create container
  hosts: target
  tasks:
  - name: web container
    docker_container:
         name: web
         image: webimage:latest
         state: started
         ports:
         - "8080:80"
         tty: true
         detach: true
